min-players: 2
max-players: 24
send-alpha-msg: true
tnttag-chat: true
#Queste opzioni verranno applicate nei mondi delle arene
world-options:
    enabled: true
    worldborder: 500.0
    #Impedire agli spectator di uscire dal border
    force-border: true
    #Consenti lo spawn di mob e animali
    allow-creature-spawn: false

countdown: 30
times-to-broadcast:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 10
    - 15
    - 20
    - 30
    - 60
    - 120

speed-level: 2

leave-item:
    name: "&cEsci dal gioco &7(Click destro)"

allowed-cmds:
    - 'tell'
    - 'msg'
    - 'w'
    - 'whisper'
    - 'r'
    - 'reply'
    - 'pe'
    - 'peremotes'
    - 'ncp'

messages:
  alpha: "&cAttenzione: Gioco ancora in fase di sviluppo. Segnalare ogni problema su /discord"
  command-denied: "&cNon puoi usare questo comando mentre sei in gioco."
  seconds-left: "&cMancano &6%sec% secondi&c!"
  second-left: "&cManca &61 secondo&c!"
  tnt-released: "&6TNT lanciata!"
  tnt-released2: "&6TNT rilanciata!"
  round-restart: "&aIl round verrà rilanciato!"
  win-message: "&8[&6TNTTag&8] &f%player% &7ha vinto una partita sulla mappa &e%arena%&7!"
  player-blowed-up: "&6%player% &cè saltato per aria!"
  player-is-it: "&f%player% &6ha la TNT!"
  tnt-given: "&aNon hai più la TNT."