name: TNTTAG
main: ml.perecraft.tnttag.TNTTag
version: 0.6
description: TNTTag di PereCraft
author: PereCraft
website: http://perecraft.ml
commands:
  tnttag:
    description: Main command
    aliases: [ttag, tt]
  tnttagadmin:
    description: Admin command
    aliases: [ttagadmin, ttadmin]
  tnttagsetup:
    description: Setup command
    aliases: [ttagsetup, ttsetup]
permissions:
  tnttag.join.arena:
   description: Permette il comando /tnttag join [arena]
   default: op
  tnttag.join.auto:
   description: Permette il comando /tnttag autojoin
   default: true
  tnttag.leave:
   description: Permette il comando /tnttag leave
   default: true
  tnttag.spectate:
   description: Permette il comando /tnttag spectate [player/arena]
   default: op
  tnttag.stats:
   description: Permette il comando /tnttag stats
   default: op
  tnttag.stats.others:
   description: Permette il comando /tnttag stats [player]
   default: op
  tnttag.admin:
   description: Permette il comando /tnttagadmin
   default: op
  tnttag.setup:
   description: Permette il comando /tnttagsetup
   default: op
  tnttag.sign.use:
   description: Permette di usare i cartelli join/leave
   default: true
  tnttag.sign.create:
   description: Permette di creare i cartelli join/leave
   default: op
  tnttag.sign.use:
   description: Permette di usare i cartelli join/leave
   default: true
  tnttag.cmdbypass:
   description: Permette di usare i comandi bloccati mentre si è in arena
   default: op